### ISSUE TITLE
有其它后续版本吗？

### ISSUE THREAD

**Issue by ericzhong2010** [elliot-bia/nessus#24] opened 2023-03-03 12:59 UTC
已经推出新版本，不知道是否会继续开拓新版本？

**Comment by elliot-bia** [comment] 2023-03-17 05:02
> 已经推出新版本，不知道是否会继续开拓新版本？

什么版本？

**Comment by elliot-bia** [comment] 2023-03-17 05:03
> Hello ... plis i need the password of nessus plis .....elliot-bia/nessus

 what do you mean? I don't get it

**Comment by leanovv** [comment] 2023-03-17 09:10
任务计划里面无法添加，点击了save无反应。

**Comment by elliot-bia** [comment] 2023-03-17 13:22
> 任务计划里面无法添加，点击了save无反应。

自行检查log

**Comment by ericzhong2010** [comment] 2023-03-26 03:40
> > 已经推出新版本，不知道是否会继续开拓新版本？
> 
> 什么版本？

最新版本10.5.0已经推出的

**Comment by zyh001** [comment] 2023-04-15 06:50
> > > 已经推出新版本，不知道是否会继续开拓新版本？
> > 
> > 
> > 什么版本？
> 
> 最新版本10.5.0已经推出的

@ericzhong2010 我根据大佬镜像制作了最新的10.5.1版本
```bash
sudo docker run --cap-add LINUX_IMMUTABLE -it -d --name nessus -p 8834:8834 stackzhao/nessus_pj:v10.5.1
# 更新插件
sudo docker exec -it nessus /bin/bash 
bash /root/upgrade.sh
# 修改默认密码
/opt/nessus/sbin/nessuscli chpasswd --user root --new-password new_password     # 请将new_password替换为新的密码
```
接下来可以使用用户`root`，密码`new_password`进行登录

**Comment by zhangzhang123-aaa** [comment] 2023-04-28 12:36
> > Hello ... plis i need the password of nessus plis .....elliot-bia/nessus
> 
> what do you mean? I don't get it

他问你登陆密码是多少

**Comment by joostgrunwald** [comment] 2023-05-04 09:48
why did you crack pro and not expert?

**Comment by joostgrunwald** [comment] 2023-05-04 11:29
> > > > 已经推出新版本，不知道是否会继续开拓新版本？
> > > 
> > > 
> > > 什么版本？
> > 
> > 
> > 最新版本10.5.0已经推出的
> 
> @ericzhong2010 我根据大佬镜像制作了最新的10.5.1版本
> 
> ```shell
> sudo docker run --cap-add LINUX_IMMUTABLE -it -d --name nessus -p 8834:8834 stackzhao/nessus_pj:v10.5.1
> # 更新插件
> sudo docker exec -it nessus /bin/bash 
> bash /root/upgrade.sh
> # 修改默认密码
> /opt/nessus/sbin/nessuscli chpasswd --user root --new-password new_password     # 请将new_password替换为新的密码
> ```
> 
> 接下来可以使用用户`root`，密码`new_password`进行登录

Secure Connection Failed

An error occurred during a connection to localhost:8835. PR_END_OF_FILE_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

**Comment by zyh001** [comment] 2023-05-04 12:56
> > > > > 已经推出新版本，不知道是否会继续开拓新版本？
> > > > 
> > > > 
> > > > 什么版本？
> > > 
> > > 
> > > 最新版本10.5.0已经推出的
> > 
> > 
> > @ericzhong2010 我根据大佬镜像制作了最新的10.5.1版本
> > ```shell
> > sudo docker run --cap-add LINUX_IMMUTABLE -it -d --name nessus -p 8834:8834 stackzhao/nessus_pj:v10.5.1
> > # 更新插件
> > sudo docker exec -it nessus /bin/bash 
> > bash /root/upgrade.sh
> > # 修改默认密码
> > /opt/nessus/sbin/nessuscli chpasswd --user root --new-password new_password     # 请将new_password替换为新的密码
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 接下来可以使用用户`root`，密码`new_password`进行登录
> 
> Secure Connection Failed
> 
> An error occurred during a connection to localhost:8835. PR_END_OF_FILE_ERROR
> 
> ```
> The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
> Please contact the website owners to inform them of this problem.
> ```

@joostgrunwald Firstly, please check if you are accessing the correct port. I noticed that you are accessing port 8835. If the address you are accessing is correct, then I believe this error is related to your browser. Could you please provide a screenshot of the error message for further analysis?

**Comment by joostgrunwald** [comment] 2023-05-04 14:45
> > > > > > 已经推出新版本，不知道是否会继续开拓新版本？
> > > > > 
> > > > > 
> > > > > 什么版本？
> > > > 
> > > > 
> > > > 最新版本10.5.0已经推出的
> > > 
> > > 
> > > @ericzhong2010 我根据大佬镜像制作了最新的10.5.1版本
> > > ```shell
> > > sudo docker run --cap-add LINUX_IMMUTABLE -it -d --name nessus -p 8834:8834 stackzhao/nessus_pj:v10.5.1
> > > # 更新插件
> > > sudo docker exec -it nessus /bin/bash 
> > > bash /root/upgrade.sh
> > > # 修改默认密码
> > > /opt/nessus/sbin/nessuscli chpasswd --user root --new-password new_password     # 请将new_password替换为新的密码
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 接下来可以使用用户`root`，密码`new_password`进行登录
> > 
> > 
> > Secure Connection Failed
> > An error occurred during a connection to localhost:8835. PR_END_OF_FILE_ERROR
> > ```
> > The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
> > Please contact the website owners to inform them of this problem.
> > ```
> 
> @joostgrunwald Firstly, please check if you are accessing the correct port. I noticed that you are accessing port 8835. If the address you are accessing is correct, then I believe this error is related to your browser. Could you please provide a screenshot of the error message for further analysis?

@zyh001 
I did a fresh reinstall to be able to reproduce better, also I have this on multiple browsers (firefox, opera, chromium) so not sure if it is a browser error. I tried the browser fixes from the internet as well so seems unrelated.

This is the entire install pipeline, I installed on 8835 because I didn't want to throw away my old install, I already had a container called nessus so I used nessus_new:

`fortifier㉿fortifier)-[~]
└─$ sudo docker run --cap-add LINUX_IMMUTABLE -it -d --name nessus_new -p 8835:8835 stackzhao/nessus_pj:v10.5.1
dedc874f7cd2c325f13bca42d5e5e2c7b86e5410de2528348c848d52a4b86da4
                                                                                
┌──(fortifier㉿fortifier)-[~]
└─$ sudo docker exec -it nessus_new /bin/bash 
root@dedc874f7cd2:~# bash /root/upgrade.sh
---------------------



 「 正在下载插件，请耐心等待。。。 」
 「 Downloading plugins, please wait....」



---------------------
--2023-05-04 14:33:14--  https://plugins.nessus.org/v2/nessus.php?f=all-2.0.tar.gz&u=56b33ade57c60a01058b1506999a2431&p=1ee9c89d5379a119a56498f2d5dff674
Resolving plugins.nessus.org (plugins.nessus.org)... 104.18.71.105, 104.18.72.105, 2606:4700::6812:4869, ...
Connecting to plugins.nessus.org (plugins.nessus.org)|104.18.71.105|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 381956492 (364M) [application/octet-stream]
Saving to: 'all-2.0.tar.gz'

all-2.0.tar.gz                                              100%[=========================================================================================================================================>] 364.26M  1.72MB/s    in 3m 6s   

2023-05-04 14:36:21 (1.96 MB/s) - 'all-2.0.tar.gz' saved [381956492/381956492]

「 文件下载成功！
download succeed! 」


{"pid":87,"time":1683210981435,"tid":1,"msg":"Warning -- could not open /usr/share/zoneinfo. Set the NESSUS_TZ_DIR env. variable","severity":"INFO"}

[info] Copying templates version 202304201313 to /opt/nessus/var/nessus/templates/tmp
[info] Finished copying templates.
[info] Moved new templates with version 202304201313 from plugins dir.
 * Update successful.  The changes will be automatically processed by Nessus.
Starting Nessus : .
---------------------



「 正在破解，请耐心等待。。。
 Cracking, please wait... 」 


「 Crack by twitter@Elliot58616851 
   && Thanks Open Source Enthusiast 」  


---------------------
正在编译中。。。请稍等
compiling...please wait
count: 0 s---------------------
Cached 0 plugin libs in 0msec
正在编译中。。。请稍等
compiling...please wait
count: 3 s---------------------
正在编译中。。。请稍等
compiling...please wait
count: 6 s---------------------
正在编译中。。。请稍等
compiling...please wait
count: 9 s---------------------
正在编译中。。。请稍等
compiling...please wait
count: 12 s---------------------
正在编译中。。。请稍等
compiling...please wait
count: 15 s---------------------
正在编译中。。。请稍等
compiling...please wait
count: 18 s---------------------
正在编译中。。。请稍等
compiling...please wait
count: 21 s---------------------
正在编译中。。。请稍等
compiling...please wait
count: 24 s---------------------
正在编译中。。。请稍等
compiling...please wait
count: 27 s---------------------
正在编译中。。。请稍等
compiling...please wait
count: 30 s---------------------
正在编译中。。。请稍等
compiling...please wait
count: 33 s---------------------
正在编译中。。。请稍等
compiling...please wait
count: 36 s---------------------
正在编译中。。。请稍等
compiling...please wait
count: 39 s---------------------
正在编译中。。。请稍等
compiling...please wait
count: 42 s---------------------
正在编译中。。。请稍等
compiling...please wait
count: 45 s---------------------
正在编译中。。。请稍等
compiling...please wait
count: 48 s---------------------
正在编译中。。。请稍等
compiling...please wait
count: 51 s---------------------
正在编译中。。。请稍等
compiling...please wait
count: 54 s---------------------
---------------------

        「 编译完成！
      compile complete! 」
---------------------
Shutting down Nessus : .
---------------------


  「 破解成功，重启中。。。
     Crack succeed, restarting...」


  「 Crack by twitter@Elliot58616851 
   && Thanks Open Source Enthusiast 」  
---------------------
Starting Nessus : .
root@dedc874f7cd2:~# 
`
firefox error
![image](https://user-images.githubusercontent.com/19670768/236243034-953f8fa8-2750-4cde-93ed-7a7bd2cb991c.png)

opera error
![image](https://user-images.githubusercontent.com/19670768/236243330-d3a595d7-00d8-4642-a387-ef36ac5209de.png)

**Comment by zyh001** [comment] 2023-05-04 15:12
> @zyh001 I did a fresh reinstall to be able to reproduce better, also I have this on multiple browsers (firefox, opera, chromium) so not sure if it is a browser error. I tried the browser fixes from the internet as well so seems unrelated.
> 
> This is the entire install pipeline, I installed on 8835 because I didn't want to throw away my old install, I already had a container called nessus so I used nessus_new:
> 
> `fortifier㉿fortifier)-[~] └─$ sudo docker run --cap-add LINUX_IMMUTABLE -it -d --name nessus_new -p 8835:8835 stackzhao/nessus_pj:v10.5.1 dedc874f7cd2c325f13bca42d5e5e2c7b86e5410de2528348c848d52a4b86da4
> 
> ## ┌──(fortifier㉿fortifier)-[~] └─$ sudo docker exec -it nessus_new /bin/bash root@dedc874f7cd2:~# bash /root/upgrade.sh
> 「 正在下载插件，请耐心等待。。。 」 「 Downloading plugins, please wait....」
> 
> --2023-05-04 14:33:14-- https://plugins.nessus.org/v2/nessus.php?f=all-2.0.tar.gz&u=56b33ade57c60a01058b1506999a2431&p=1ee9c89d5379a119a56498f2d5dff674 Resolving plugins.nessus.org (plugins.nessus.org)... 104.18.71.105, 104.18.72.105, 2606:4700::6812:4869, ... Connecting to plugins.nessus.org (plugins.nessus.org)|104.18.71.105|:443... connected. HTTP request sent, awaiting response... 200 OK Length: 381956492 (364M) [application/octet-stream] Saving to: 'all-2.0.tar.gz'
> 
> all-2.0.tar.gz 100%[=========================================================================================================================================>] 364.26M 1.72MB/s in 3m 6s
> 
> 2023-05-04 14:36:21 (1.96 MB/s) - 'all-2.0.tar.gz' saved [381956492/381956492]
> 
> 「 文件下载成功！ download succeed! 」
> 
> {"pid":87,"time":1683210981435,"tid":1,"msg":"Warning -- could not open /usr/share/zoneinfo. Set the NESSUS_TZ_DIR env. variable","severity":"INFO"}
> 
> [info] Copying templates version 202304201313 to /opt/nessus/var/nessus/templates/tmp [info] Finished copying templates. [info] Moved new templates with version 202304201313 from plugins dir.
> 
> * Update successful.  The changes will be automatically processed by Nessus.
>   Starting Nessus : .
> 
> 「 正在破解，请耐心等待。。。 Cracking, please wait... 」
> 
> 「 Crack by twitter@Elliot58616851 && Thanks Open Source Enthusiast 」
> 
> ## 正在编译中。。。请稍等
> compiling...please wait
> count: 0 s---------------------
> Cached 0 plugin libs in 0msec
> 正在编译中。。。请稍等
> compiling...please wait
> count: 3 s---------------------
> 正在编译中。。。请稍等
> compiling...please wait
> count: 6 s---------------------
> 正在编译中。。。请稍等
> compiling...please wait
> count: 9 s---------------------
> 正在编译中。。。请稍等
> compiling...please wait
> count: 12 s---------------------
> 正在编译中。。。请稍等
> compiling...please wait
> count: 15 s---------------------
> 正在编译中。。。请稍等
> compiling...please wait
> count: 18 s---------------------
> 正在编译中。。。请稍等
> compiling...please wait
> count: 21 s---------------------
> 正在编译中。。。请稍等
> compiling...please wait
> count: 24 s---------------------
> 正在编译中。。。请稍等
> compiling...please wait
> count: 27 s---------------------
> 正在编译中。。。请稍等
> compiling...please wait
> count: 30 s---------------------
> 正在编译中。。。请稍等
> compiling...please wait
> count: 33 s---------------------
> 正在编译中。。。请稍等
> compiling...please wait
> count: 36 s---------------------
> 正在编译中。。。请稍等
> compiling...please wait
> count: 39 s---------------------
> 正在编译中。。。请稍等
> compiling...please wait
> count: 42 s---------------------
> 正在编译中。。。请稍等
> compiling...please wait
> count: 45 s---------------------
> 正在编译中。。。请稍等
> compiling...please wait
> count: 48 s---------------------
> 正在编译中。。。请稍等
> compiling...please wait
> count: 51 s---------------------
> 正在编译中。。。请稍等
> compiling...please wait
> count: 54 s---------------------
> ```
>     「 编译完成！
>   compile complete! 」
> ```
> 
> ## Shutting down Nessus : .
> 「 破解成功，重启中。。。 Crack succeed, restarting...」
> 
> ## 「 Crack by twitter@Elliot58616851
> && Thanks Open Source Enthusiast 」
> Starting Nessus : . root@dedc874f7cd2:~# ` firefox error ![image](https://user-images.githubusercontent.com/19670768/236243034-953f8fa8-2750-4cde-93ed-7a7bd2cb991c.png)
> 
> opera error ![image](https://user-images.githubusercontent.com/19670768/236243330-d3a595d7-00d8-4642-a387-ef36ac5209de.png)

@joostgrunwald It looks good and the installation process seems to be normal.  I think this could be caused by incorrect SSL configuration. You can try resetting your Firefox SSL settings. 

* To reset your SSL settings, head to the “hamburger” menu within Firefox and click the **Help** option.
* From here, select **More Troubleshooting Information**. This will pop a screen up in-browser showing some diagnostics.
* Here, click the **Refresh Firefox** button, and your browser will restart. This is enough to reset your SSL settings, so check out whether you can browse the web at this point. If not, there is another technical fix we can carry out.

Please try the above steps and leave another message after attempting them.

**Comment by joostgrunwald** [comment] 2023-05-04 15:20
![image](https://user-images.githubusercontent.com/19670768/236253162-9f5f818f-1156-48df-841c-29ba694fbfc7.png)

**Comment by zyh001** [comment] 2023-05-04 15:41
> @zyh001 didn't help, after connecting with http on firefox I get the same issue as on opera: ![image](https://user-images.githubusercontent.com/19670768/236252072-3031ac90-4fd5-46f5-bceb-0fa055ea202b.png)
> 
> Interesting behaviour on opera and chromium is that it switches constantly from the side can not be reached to ![image](https://user-images.githubusercontent.com/19670768/236252412-ab82c405-e92c-4561-b715-e346e74dab6f.png)
> 
> and back

@joostgrunwald 
This doesn't look good. I just tried redeploying a container and couldn't reproduce your issue. Please confirm if the Nessus service inside the container is running properly.

You can use the `docker exec` command to enter the container, for example:

```
docker exec -it your_container /bin/bash
```

This will enter the `your_container` container and open an interactive bash shell. Inside the container, you can use regular command-line tools to check if the services are running, such as using the `ps -aux` command to view running processes, or executing service-specific commands to check their status.

**Comment by joostgrunwald** [comment] 2023-05-04 19:07
└─$ sudo docker exec -it nessus_new /bin/bash 
root@dedc874f7cd2:~# ls
install.sh  run.sh  start.sh  upgrade.sh
root@dedc874f7cd2:~# ps
bash: ps: command not found
root@dedc874f7cd2:~# top
bash: top: command not found
root@dedc874f7cd2:~# htop
bash: htop: command not found @zyh001 I'll try the nessuscli and services

**Comment by joostgrunwald** [comment] 2023-05-04 19:15
hmm might be related to the actual port change on both sides :) sudo docker run --cap-add LINUX_IMMUTABLE -it -d --name newnessus -p 7272:8834 stackzhao/nessus_pj:v10.5.1  , I am now trying this

**Comment by elliot-bia** [comment] 2023-05-05 02:10
I am glad you had fix this problem, the Nessus Scan using default port **8834**, next time using the follow command：  
`sudo docker run --cap-add LINUX_IMMUTABLE -it -d --name nessus_new -p 8835:8834 stackzhao/nessus_pj:v10.5.1`  
Please notice the **docker mapping relation**: `-p 8835:8834` port 8835 on the Docker host, mapping port 8834 in the container.  You can get more info from [docker.com](https://docs.docker.com/config/containers/container-networking/)

And now I will close this thread

**Closed by elliot-bia** 2023-05-05 02:10 UTC
